language: node_js
node_js:
- node
os:
- osx
cache:
  directories:
  - "~/.npm"
  - "~/Library/Caches/electron/"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_8c127902616b_key -iv $encrypted_8c127902616b_iv
  -in cert.p12.enc -out cert.p12 -d
before_script: ./import_osx_cert.sh
script: npm run publish
env:
  global:
    secure: 0MCNf3KOam+ig1qje/cSFutMlJDWXjWJJiIQO0+maVASyA6a7LdUHhriGAr8JB88NYlYHmOBBmXH7IUG2ubYnyaUQJeHtc6e4b4By1s9OgA+guaU8u0CyUO80zLqy8VhsMs1PHww4eQkfGdrhU/rXUUaIpbKOmrRLlI2EctBX/UzmIkk4qzrF52lqXqkVIatxaYmpjaBg1tPsErdYbjg8J+Edc/pPS44F4hnKf9+jXJ24JGsPSZUWabH5fhcnslQMMunuOfyiaqgrrD/HaLLlOcUmhRVfp1qnckC4cJ+faXevUKAGSbIgb25Fs74L63sAhcb9UbOisgroySCmgNp4jrkrv0ZXcuSwgtJEm8HJJK4R2VNUy87yLWfxn/19jJORzqH4Pb6krHRPZM/slK4aWzsPmOsvLIXUjZVI6EKrkOqtka6SFxFlgAhmibM/L6Q+9/iqu+QE5MyEvuvOLeBknRxVerEv7UoXRw4K3mzgHgRJ7ESv1kzleTaG3U9HcO7i7GdIPFEVEalQgAUSeHBa5xDV/vi1VKMPElhWQtjI2LtNV7dSAuXocBpkiG5RX5BL87vCv/YscBUvlJPOBqh+UlizxSsTw4BxEo4fB0zoK0WbZH33um8NThS+OaCti29sKfD26gg8ufMYT8N+9knTAmg2JhWOUUbelObsNUO80Q=
