platform:
- x64
environment:
  nodejs_version: "stable"
  GITHUB_TOKEN:
    secure: P3PUvll7sdLjanWtuI2fBxKqZi4dIKbzeokpLape1l9qm2PWB17/znIx4zcBvEgY
cache:
- '%APPDATA%\npm-cache'
- '%LOCALAPPDATA%\electron\Cache'
branches:
  only:
  - master
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - npm install -g npm@4
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build_script:
  - npm run make
after_build:
  - ps: Get-ChildItem .\out\make | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off